---
- name: Insert flannel configuration into etcd
  command: |-
    {{ etcd_bin_dir }}/etcdctl --ca-file={{ etcd_peer_ca_file }} \
    --cert-file={{ etcd_peer_cert_file }} --key-file={{ etcd_peer_key_file }} \
    set {{ flannel_key}}  \
    '{"Network":"{{ flannel_network}}","SubnetLen":{{ flannel_subnet_len }},"Backend":{"Type":"{{ flannel_backend_type}}"}}' 
  delegate_to: "{{ groups['etcd'][0] }}"
  run_once: yes


- debug: var="{{ ansible_default_ipv4.address }}"

- name: Create the flannel log directory
  file:
    path: "{{ item }}" 
    state: directory
    mode: 0755
  with_items:
    - "{{ flannel_log_dir }}"
    - "{{ flannel_conf_dir }}"
    - "{{ flannel_bin_dir }}"
    - /usr/lib/systemd/system/docker.service.d

- name: Copy binary to node instance
  get_url:
    url: "https://s3.cn-north-1.amazonaws.com.cn/k8s/ansible/flanneld/v0.7.1/{{ item }}"
    dest: "{{ flannel_bin_dir }}/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - flanneld
    - mk-docker-opts.sh


- name: Create a system unit file
  template:
    src: "{{ role_path }}/templates/flanneld.service"
    dest: /usr/lib/systemd/system/flanneld.service
    owner: root
    group: root
    mode: 0644
  register: change_flannel_system

- name: Create the flanneld configuration file
  template:
    src: "{{ role_path }}/templates/flanneld.conf"
    dest: "{{ flannel_conf_dir }}/flanneld"
    owner: root
    group: root
    mode: 0644
  register: change_flannel_config

- name: Configure environment variables for docker
  # flanneld 启动时将网络配置写入到 /run/flannel/docker 文件中的变量
  # DOCKER_NETWORK_OPTIONS，dockerd 命令行上指定该变量值来设置 docker0
  # 网桥参数；
  # 如果在启动配置文件指定了多个 EnvironmentFile 选项，则必须将
  # /run/flannel/docker 放在最后
  template:
    src: "{{ role_path }}/templates/docker.service.d/flannel.conf"
    dest: "/usr/lib/systemd/system/docker.service.d/flannel.conf"
    owner: root
    group: root
    mode: 0644

- name: start and enable flannel on node
  when: change_flannel_system|succeeded and change_flannel_config|succeeded
  systemd:
    name: flanneld
    enabled: true
    state: started
  notify:
    - restart docker

- name: reload flanneld
  when: change_flannel_system|changed or change_flannel_config|changed
  systemd:
    name: flanneld
    state: restarted
    daemon_reload: true
  notify:
    - restart docker
